<?php

define('HEXAGON_LOG_LEVEL_DEBUG', 0b0000001);
define('HEXAGON_LOG_LEVEL_NOTICE', 0b0000010);
define('HEXAGON_LOG_LEVEL_INFO', 0b0000100);
define('HEXAGON_LOG_LEVEL_WARN', 0b0001000);
define('HEXAGON_LOG_LEVEL_ERROR', 0b0010000);
define('HEXAGON_LOG_LEVEL_FATAL', 0b0100000);
define('HEXAGON_LOG_LEVEL_EMERGENCY', 0b1000000);
define('HEXAGON_LOG_LEVEL_NONE', 0);
define('HEXAGON_LOG_LEVEL_ALL', 0b1111111);
define('HEXAGON_LOG_LEVEL_PRODUCTION', 0b1111110);

define('HEXAGON_LOG_MATCH_ALL', 0);
define('HEXAGON_LOG_MATCH_MODE_WILDCARD', 1);
define('HEXAGON_LOG_MATCH_MODE_RE', 2);

define('HEXAGON_URI_PROTOCOL_AUTO', 0);
define('HEXAGON_URI_PROTOCOL_PATH_INFO', 1);
define('HEXAGON_URI_PROTOCOL_QUERY_STRING', 2);
define('HEXAGON_URI_PROTOCOL_REQUEST_URI', 3);

$testMode = defined('HEXAGON_TEST_MODE') ? HEXAGON_TEST_MODE : false;
if (php_sapi_name() === 'cli' && !$testMode) {
    define('HEXAGON_CLI_MODE', TRUE);
} else {
    define('HEXAGON_CLI_MODE', FALSE);
}
