<?php

define('HEXAGON_LOG_LEVEL_DEBUG', 0b00001);
define('HEXAGON_LOG_LEVEL_INFO', 0b00010);
define('HEXAGON_LOG_LEVEL_WARN', 0b00100);
define('HEXAGON_LOG_LEVEL_ERROR', 0b01000);
define('HEXAGON_LOG_LEVEL_FATAL', 0b10000);
define('HEXAGON_LOG_LEVEL_NONE', 0);
define('HEXAGON_LOG_LEVEL_ALL', HEXAGON_LOG_LEVEL_DEBUG | HEXAGON_LOG_LEVEL_INFO | HEXAGON_LOG_LEVEL_WARN | HEXAGON_LOG_LEVEL_ERROR | HEXAGON_LOG_LEVEL_FATAL);
define('HEXAGON_LOG_LEVEL_PRODUCTION', HEXAGON_LOG_LEVEL_INFO | HEXAGON_LOG_LEVEL_WARN | HEXAGON_LOG_LEVEL_ERROR | HEXAGON_LOG_LEVEL_FATAL);

define('HEXAGON_URI_PROTOCOL_AUTO', 0);
define('HEXAGON_URI_PROTOCOL_PATH_INFO', 1);
define('HEXAGON_URI_PROTOCOL_QUERY_STRING', 2);
define('HEXAGON_URI_PROTOCOL_REQUEST_URI', 3);

if (php_sapi_name() === 'cli') {
    define('HEXAGON_CLI_MODE', TRUE);
} else {
    define('HEXAGON_CLI_MODE', FALSE);
}